baseURL: 'https://sol-et-co.netlify.com'
languageCode: fr-fr
title: Sol & Co
theme: sol-et-co
DefaultContentLanguage: fr

params:
  author: Yop
  dateFormat: 'Jan 2, 2006'


menu:
  main:
    - name: Prestations
      url: /prestations/
      weight: 1
    - name: Réalisations
      url: /realisations/
      weight: 2
    - name: Compétences
      url: /competences/
      weight: 3
    - name: Qui sommes-nous
      url: /qui-sommes-nous/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
  footer:
    - name: Prestations
      url: /prestations/
      weight: 1
    - name: Réalisations
      url: /realisations/
      weight: 2
    - name: Compétences
      url: /competences/
      weight: 3
  footer_02:
    - name: Qui sommes-nous
      url: /qui-sommes-nous/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
    - name: Mentions légales
      url: /mentions/
      weight: 6

permalinks:
  pages: '/:filename/'

taxonomies:
  category: categories
  tag: tags

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: prestation_key
    weight: 1